version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testtech
    networks:
      - abdel
  test-db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testtech
    networks:
      - abdel
networks:
  abdel:
